### ISSUE TITLE
That was a blast!

### ISSUE THREAD

**Issue by 0xScratch** [ATrnd/GridChainGames#3]
As a dev, I feel we should have an engagement with fellow developers and look out for what cool stuff they are doing within their own precious time. That's why apart from participating in Backdrop, a side activity I do is look for potential projects and appreciate what they did (plus, it also adds to cool ideas, problems, and sometimes even solutions)

Talking about GCG, the demo was seriously amazing, the idea is really good, one of the most consistent updates...
Web 3.0 gaming demands really great devs, solutions, working such that it kind of becomes hard to even detect this game is running on the blockchain. Apart from that, we need extra security, accessibility, and protocols. I also feel we shouldn't really think of Web 3.0 gaming as something different from Web 2.0, the people running those organizations have done mind-blowing breakthroughs in the past...all we need is power Web2.0 games with blockchain capability to make it more effective, decentralized and something which players can own...That's just my small view of the problem right now, you have a lot better ideas and this was a demo...

Congratulations on launching it down mate!

**Comment by ATrnd** [comment]
Thanks for the kind words, mate.
I love games, but I love designing games even more.
GCG is the Seed of something big; I'll push it as hard as possible and make it a reality.
Again, thank you for the encouragement.

Regards, A

**Comment by 0xScratch** [comment]
Builders Support Builders!
